[versions]
agp = "8.9.1"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
lottieV = "4.2.1"
googleServiceV = "4.4.2"
firebaseAuthV = "23.2.0"
firebaseDatabaseV = "21.0.0"
imagePickerV = "2.1"
glideV = "4.16.0"
storageV = "21.0.1"
authGoogleV = "21.0.0"
ccpV = "2.7.0"
photoViewV = "2.3.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lottie = {group = "com.airbnb.android", name = "lottie", version.ref = "lottieV"}
firebaseAuth = {group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuthV"}
firebaseDatabase = {group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabaseV"}
imagePicker = {group = "com.github.dhaval2404", name = "imagepicker", version.ref = "imagePickerV"}
glide = {group = "com.github.bumptech.glide", name = "glide", version.ref = "glideV"}
storage = {group = "com.google.firebase", name = "firebase-storage", version.ref = "storageV"}
authGoogle = {group = "com.google.android.gms", name = "play-services-auth", version.ref = "authGoogleV"}
ccp = {group="com.hbb20", name="ccp", version.ref="ccpV"}
photoView = {group="com.github.chrisbanes", name="PhotoView", version.ref="photoViewV"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleService = {id = "com.google.gms.google-services", version.ref = "googleServiceV"}


